version: '3.8'
services:
  db:
    container_name: ssm_postgres
    image: postgres:16
    environment:
      POSTGRES_DB: ssm_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password 
    ports:
      - "5432:5432"
    volumes:
      - ssm_data:/var/lib/postgresql/data

volumes:
  ssm_data: